### ISSUE TITLE
Remove CloudFlare Protection, API now is useless

### ISSUE THREAD

**Issue by jamiekarvans** [radude/rentry#28] opened 2024-05-08 05:20 UTC
Hi, please remove cloudflare protection on rentry.co, everytime user tries to edit or take the raw text in all my apps now failing, since it asks to check the robot field.
i don't understand what's the point of putting such a thing for such a service and website?

**Comment by KaladinDMP** [comment] 2024-05-08 07:18
Im having the same issue, all my scripts failing even the ones that just read the raw text

**Comment by KaladinDMP** [comment] 2024-05-08 07:27
Dupe of #27  apparently its temperary

**Comment by radude** [comment] 2024-05-08 09:45
Please bear with us, we're getting hit relentlessly by DDOS attacks and are working hard to find the balance to mitigate these attacks and keep the API working. 
Please do keep making issues however if these persist as we need the feedback to ensure we get the balance correct.

**Comment by KaladinDMP** [comment] 2024-05-08 19:55
Thank you, i ran one of my scripts just now and it completed for the first time in a day or 2. Seems to be back to normal. imo this can be closed

**Comment by jamiekarvans** [comment] 2024-05-08 20:00
Yes, it seems to be working now.
Thanks for the efforts to making it work again.

**Closed** 2024-05-08 22:36 UTC
